"""Render docs/stock_research/HYPOTHESIS_REGISTRY.md from the registered specs.

The document is generated, never edited: the specifications in code are what
the protocol hash covers, and a hand-written copy would drift from them.

    python -m stock_research.registry_doc
"""

from __future__ import annotations

from stock_research.config import REPOSITORY_ROOT
from stock_research.hypotheses import common, registry

TARGET = REPOSITORY_ROOT / "docs" / "stock_research" / "HYPOTHESIS_REGISTRY.md"


def render() -> str:
    lines = [
        "# Hypothesis registry",
        "",
        "*Generated by `python -m stock_research.registry_doc` from the specifications "
        "in `stock_research/hypotheses/`. Do not edit by hand. The protocol hash "
        "printed by `python -m stock_research.cli status` covers these specifications, "
        "every rule version, every constant and the source files themselves.*",
        "",
        f"Protocol version: `{registry.PROTOCOL_VERSION}`. Primary family: "
        f"{common.FAMILY_SIZE} hypotheses, Holm-adjusted together whether or not all "
        "can run.",
        "",
        "## Verdict rule",
        "",
        registry.VERDICT_RULE.capitalize(),
        "",
        "A verdict may be reported as a finding only from real historical data on a "
        "complete sample frame.",
        "",
    ]
    for key, spec in registry.SPECS.items():
        sign = "positive" if spec.direction > 0 else "negative"
        lines += [
            f"## {key}: {spec.title}",
            "",
            f"**Claim.** {spec.claim}",
            "",
            "| | |",
            "|---|---|",
            f"| Null | {spec.null} |",
            f"| Alternative | {spec.alternative} |",
            f"| Eligibility | {spec.eligibility} |",
            f"| Event time | {spec.event_time} |",
            f"| Outcome | {spec.outcome} |",
            f"| Primary estimand | {spec.estimand} |",
            f"| Hypothesised sign | {sign} |",
            f"| Material effect | {spec.material_effect} |",
            f"| Benchmark | {spec.benchmark} |",
            f"| Controls | {', '.join(spec.controls) or 'none'} |",
            f"| Inference | {spec.inference} |",
            f"| Sample-size rules | {'; '.join(f'{k} = {v}' for k, v in spec.sufficiency.items())} |",
            f"| Data required | {', '.join(spec.requires)} |",
            f"| Multiple testing | {spec.multiple_testing} |",
            f"| Sensitivity analyses | {'; '.join(spec.sensitivity) or 'none'} |",
            f"| Depends on an unverifiable fill | {'yes' if spec.execution_dependent else 'no'} |",
            f"| Parameters | {'; '.join(f'{k} = {v}' for k, v in spec.parameters.items())} |",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
